### ISSUE TITLE
input accept 改为自定义吗

### ISSUE THREAD

**Issue by ft234451532** [Vanthink-UED/vue-core-image-upload#1]
默认accept="image/*" 在chome 53，每次点击都需要等几秒才可以打开
设置成accept="image/jpg,image/jpeg,image/png"一下就打开了

**Comment by JackPu** [comment]
OK，@ft234451532 谢谢反馈，我们更新后提示你。

**Comment by angusjiang** [comment]
@ft234451532 在什么设备上打开慢，我这边偶尔会出现过，但是accept="image/*" 与 accept="image/jpg,image/jpeg,image/png" 二者并不会对打开速度有影响？

**Comment by ft234451532** [comment]
@angusjiang  Windows 10 + Chrome 53, 在开发工具Elements里修改accept效果明显

firefox 使用没问题
