### ISSUE TITLE
注意！2.3.5版本编译文件有问题 import rotate-bar缺少.vue后缀

### ISSUE THREAD

**Issue by mkzxcvbnm** [Vanthink-UED/vue-core-image-upload#106]
![image](https://user-images.githubusercontent.com/16659155/28487286-036e3d84-6ec0-11e7-9024-bd5a7dfdb532.png)
需要手动修改vue-core-image-upload\dist\crop.vue 第136行  修改成“import RotateBar from './rotate-bar.vue';”

**Comment by JackPu** [comment]
这个bug 已经修复了，感谢支持~ ❀
