### ISSUE TITLE
不支持iphone手机照片.mov格式的的动态图片的上传

### ISSUE THREAD

**Issue by davy-gan** [Vanthink-UED/vue-core-image-upload#109]
能否增加功能支持iphone照片.mov格式的上传  或者上传前将.mov转换成jpg之类的格式上传

**Comment by davy-gan** [comment]
接收图片类型这里是不是多了一个点，应该是逗号
![572d9063-12c0-4e48-9efb-cb223397a73e](https://user-images.githubusercontent.com/21240946/28568029-f40be144-7166-11e7-932e-210192398a07.png)

**Comment by JackPu** [comment]
是的，应该是点

**Comment by JackPu** [comment]
Thanks a lot~

**Comment by JackPu** [comment]
这个.mov 我还需要研究下。目前不支持。
