### ISSUE TITLE
关于错误处理的问题

### ISSUE THREAD

**Issue by yoqu-in** [Vanthink-UED/vue-core-image-upload#116]
我看了下代码,貌似是返回了一段字符串(英文).
不过我这边的需求是根据错误类型提示中文,例如"上传的文件类型错误"  "上传的图片太大之类".
目前我是用indexOf 来判断某些关键字来确定错误类型.
请问有什么更好的解决方案吗?

**Comment by zhangyuanze** [comment]
我也碰到了这个问题

**Comment by JackPu** [comment]
Megre this https://github.com/Vanthink-UED/vue-core-image-upload/issues/161
