### ISSUE TITLE
请问，当isXhr 为false的时候，如何自己上传图片，在哪个响应里面上传图片？

### ISSUE THREAD

**Issue by OBKoro1** [Vanthink-UED/vue-core-image-upload#118]
如题，求大佬指点。

**Comment by JackPu** [comment]
详情参考这篇文章 http://www.jackpu.com/qu-xiao-vue-core-image-upload-de-mo-ren-shang-chuan/

**Comment by OBKoro1** [comment]
谢谢大佬，根据这篇文章已经写出来了。目前遇到了一个新问题，请问这个插件，可以支持修改裁剪的样式么？指的是裁剪界面的样式。。按钮希望放在左下角，以及做一些符合项目的样式调整。

**Comment by OBKoro1** [comment]
http://vanthink-ued.github.io/vue-core-image-upload/index.html#/cn/events 大佬，您插件文档中报错了。图片上传都失败了。
