### ISSUE TITLE
跨域问题，设置credentials 跨域属性值为true无法也无法成功跨域

### ISSUE THREAD

**Issue by OBKoro1** [Vanthink-UED/vue-core-image-upload#125]
XMLHttpRequest cannot load http://192.168.10.139:8088/a/uploadImage. **No 'Access-Control-Allow-Origin' header is present on the requested resource.** Origin 'http://localhost:8088' is therefore not allowed access. The response had HTTP status code 400.

**Comment by OBKoro1** [comment]
![image](https://user-images.githubusercontent.com/24698201/29362128-3a6cbf48-82bd-11e7-8ae5-4f4284b9960c.png)
这里是代码，上面是报错内容

**Comment by mahuanhuan** [comment]
设置为false 就可以了 ，你试试

**Comment by OBKoro1** [comment]
@mahuanhuan 大佬，并不行，设置false还是跨域问题，同一个报错。

**Comment by Hiber0385** [comment]
跨域头信息 Access-Control-Allow-Origin  为  *   时  Access-Control-Allow-Credentials 设置为true 就是会报错,解决的办法就是后端将请求的域名设置在  Access-Control-Allow-Origin 中,不要用 *

**Comment by GoogleCodes** [comment]
请问有没有具体代码？
