### ISSUE TITLE
Events are not handled

### ISSUE THREAD

**Issue by vrajroham** [Vanthink-UED/vue-core-image-upload#13]
#### Getting

Using NPM I pulled the package, I am using webpack to combine.
Everything is working fine except event handling. I debugged and found that events are being dispatched but not being handle or captured.
I am using vuejs 2.1.4.
Using ES6 syntax

#### Expected 

Events should be handled.

**Comment by JackPu** [comment]
Cloud you show some your vue template code?

**Comment by vrajroham** [comment]
###Script

```javascript
	import VueCoreImageUpload from 'vue-core-image-upload';
	export default {
	    components: {
	        'vue-core-image-upload': VueCoreImageUpload
	    },
	    data() {
	        return {
	            src: 'http://img1.vued.vanthink.cn/vued0a233185b6027244f9d43e653227439a.png',
	        }
	    },
	    events: {
	        imageuploaded(res) {
	            if (res.errcode == 0) {
	                this.src = '';
	            }
	        }
	    }
	}
```


###HTML Template

```html
<img class="avatar" v-bind:src="src"/>
		<vue-core-image-upload 
			v-bind:class="['ui mini blue button']" 
			v-bind:crop="true"
			v-bind:cropBtn="{ 'ok':'CROP AND UPLOAD','cancel':'CANCEL' }" 
			url="profile-image" 
			extensions="png,gif,jpeg,jpg"	
			></vue-core-image-upload>
```

**Comment by vrajroham** [comment]
Events are being dispatched

![screenshot from 2017-02-11 18 51 39](https://cloud.githubusercontent.com/assets/12662173/22854100/670f419c-f08c-11e6-87e4-3b88e9f1f639.png)

**Comment by vrajroham** [comment]
#### I managed to find workaround as below.

Manually add event listener on component as 
`v-on:imageuploaded = "imageuploaded"`
```html
<vue-core-image-upload 
			v-bind:class="['ui mini blue button']" 
			v-bind:crop="true"
			v-bind:cropBtn="{ 'ok':'CROP AND UPLOAD','cancel':'CANCEL' }" 
			url="profile-image" 
			extensions="png,gif,jpeg,jpg"	
			v-on:imageuploaded="imageuploaded"
			></vue-core-image-upload>
```

`imageuploaded()` moved from events to methods

But `res` (response) returns **only data** which is returned by server as array. 
so i directly assigned returned response toi source which works in my case.

```javascript
	    methods:{
	       imageuploaded(res) {	           
	                this.src = res;
	        },
              }
```

Hope there would be better alternative.

**Comment by JackPu** [comment]
I has updated my README.md. Your script is correct.

**Comment by vrajroham** [comment]
As it's working after workaround so, closing the issue. If occurs in future then reopen it again.
