### ISSUE TITLE
webpack编译出错

### ISSUE THREAD

**Issue by zhouxinkai** [Vanthink-UED/vue-core-image-upload#14]
![snip20170213_2](https://cloud.githubusercontent.com/assets/13215870/22870056/fd069152-f1de-11e6-8f00-3714553e4d5e.png)
![snip20170213_1](https://cloud.githubusercontent.com/assets/13215870/22870055/fd06331a-f1de-11e6-8d17-428902cb7372.png)
而去掉下面这个代码片段，将不会出错
```JavaScript
  components: {
    VueCoreImageUpload,
  },
```

**Comment by JackPu** [comment]
你改成这样试下可以么？
export default {
  components: {
    'vue-core-image-upload': VueCoreImageUpload
  }
}
