### ISSUE TITLE
Blurred out cropped part

### ISSUE THREAD

**Issue by JackPu** [Vanthink-UED/vue-core-image-upload#16]
@warmjaijai said: 

Hi again, it actually looks abnormal to me for the part of the image being cropped blurred out instead of the part outside of the cropping square. Is there anyway to reverse that setting?

**Comment by warmjaijai** [comment]
Somehow I came to this package again and found this... I hope this issue will get some attentions.

**Comment by JackPu** [comment]
@warmjaijai  I'll handle it soon. Can you tell me your facebook  or wechat to get more details.
