### ISSUE TITLE
Vue 2.1.10 issues

### ISSUE THREAD

**Issue by Drachenfels** [Vanthink-UED/vue-core-image-upload#18]
Hi guys, I just followed demo and I am receiving tons of errors related to this component:

`[Vue warn]: Invalid default value for prop "class": Props with type Object/Array must use a factory function to return the default value. `

`[Vue warn]: Component template should contain exactly one root element:`

`[Vue warn]: failed to compile template: <tons-of-text> - avoid using JavaScript keyword as property name: "class" in expression v-bind:class="class"`

**Comment by Drachenfels** [comment]
My question is, is it something on my side or this plugin is just not working in this version of vue?

**Comment by JackPu** [comment]
@Drachenfels  I'll test it and give u a reply soon.

**Comment by Sapphire2k** [comment]
[Vue warn]: Invalid default value for prop "class": Props with type Object/Array must use a factory function to return the default value.

change the component's default value
Change: default: {}
To: default: function() {
                  return {}
}

[Vue warn]: Component template should contain exactly one root element:
In Component:
<template>
    <div></div>   // only allow one div
</template>

[Vue warn]: failed to compile template: <tons-of-text> - avoid using JavaScript keyword as property name: "class" in expression v-bind:class="class"
...change "<tons-of-text v-bind:class="class"> " property "v-bind:class" 's value [class].. no keyword 
like this:
<tons-of-text v-bind:class="demoClass">

**Comment by JackPu** [comment]
We have update new document here: http://vanthink-ued.github.io/vue-core-image-upload/index.html#/en/home
