### ISSUE TITLE
图片裁切和压缩问题

### ISSUE THREAD

**Issue by Ken-Zhao** [Vanthink-UED/vue-core-image-upload#182]
1、local本地裁切上传报错，用server没问题；
2、压缩限制了格式，png和gif不让压缩，而其他格式压缩后图片全黑，把格式限制去年后再压缩上传，就都黑了：
if (this.compress && this.files[0]['type'] !== 'image/png' && this.files[0]['type'] !== 'image/gif') {
          daycaca.compress(this.files[0], 100 - this.compress, (code) => {
            this.tryAjaxUpload('', true, code);
          });
        } else {
          this.tryAjaxUpload();
        }

这两个问题，我猜测都跟那个code有关，转base64后有问题。

**Comment by hairichuhe** [comment]
及解决了吗，我也遇到这个问题了，好郁闷

**Comment by Ken-Zhao** [comment]
解决了，
第1个，我用的server，还是在服务端裁切的；
第2个，原组件压缩后的数据格式有问题，部分浏览器是不支持的，后来另加了一个压缩插件，两个结合了一个就解决了。

**Comment by hairichuhe** [comment]
嗯嗯，我用了简单粗暴的办法，退回到2.3.6版本了，没有啥问题。。

**Comment by WEBSFAN** [comment]
@hairichuhe 我想问一下，图片压缩的时候出现问题，版本回退2.3.6就可以吗？
