### ISSUE TITLE
 Cannot read property 'value' of null on change image

### ISSUE THREAD

**Issue by RodrigoAngeloValentini** [Vanthink-UED/vue-core-image-upload#183]
Uncaught TypeError: Cannot read property 'value' of null;

`change: function change(e) {
      var fileVal = document.querySelector('#g-core-upload-input-' + this.formID).value.replace(/C:\\fakepath\\/i, "");
}`

**Comment by hairichuhe** [comment]
v2.2.4 is no this proble...

**Comment by licong96** [comment]
It was good before, but not now.

![vue-core-image-upload 3](https://user-images.githubusercontent.com/28621732/36715419-191131d2-1bd1-11e8-9828-5d6d75afb517.png)
![vue-core-image-upload 2](https://user-images.githubusercontent.com/28621732/36715464-4b071cf6-1bd1-11e8-90e9-60e23ee7bc59.png)
![vue-core-image-upload 1](https://user-images.githubusercontent.com/28621732/36715469-5394c42c-1bd1-11e8-8455-c74576775473.png)

**Comment by meta0102** [comment]
same

**Comment by licong96** [comment]
我用了 `cnpm cache clean -f` 清除缓存，然后再次安装之后又可以了

**Comment by Jquery-love** [comment]
找到 包目录 vue-core-image-upload/dist/vue-core-image-upload.vue  把这个文件用vue-core-image-upload/src/vue-core-image-upload.vue  替换下  就好了

**Comment by mumu1993** [comment]
还真是 为啥会这样呢

**Comment by JackPu** [comment]
@mumu1993  @Jquery-love @RodrigoAngeloValentini The bug fixed in 2.4.4 .

Thanks for @Jquery-love issue. 🌹
