### ISSUE TITLE
上传图片报错

### ISSUE THREAD

**Issue by gaoyujie** [Vanthink-UED/vue-core-image-upload#193]
在github里点击demo进入文档里，点击里面任意的上传按钮，选择好文件后报错，用的是谷歌浏览器，版本号是65
![image](https://user-images.githubusercontent.com/20085731/38796713-cab0d220-418e-11e8-90f5-435bc9421eeb.png)

**Comment by zgj233** [comment]
我也是啊，之前程序一直都是好好的。后来就报这个错了，莫非是chrome 版本的问题？

**Comment by tower1229** [comment]
示例都报错，咋回事？

**Comment by JackPu** [comment]
文档 这个bug fixed! https://github.com/Vanthink-UED/Vanthink-UED.github.io/commit/b27b6ac9de6280cd201cc1cf471c0816c2a95baa
