### ISSUE TITLE
credentials 默认值问题

### ISSUE THREAD

**Issue by 565784135** [Vanthink-UED/vue-core-image-upload#196]
"vue-core-image-upload": "^2.4.5"
使用的是这个版本，需要手动设置 :credentials="false"
不然上传会默认带上cookie
会造成跨域问题，和后台撕逼了一天。。。。。
不带这么坑的

**Comment by WilliamLin1990** [comment]
@565784135 我前几天也是这样，太痛苦了，用的是图床，无法在服务器端查看原因，现在还有本地裁剪黑图片的问题。

**Comment by 565784135** [comment]
@WilliamLin1990     唉，谁让咱们是伸手党，认了吧

**Comment by zgj233** [comment]
@WilliamLin1990  本地裁剪黑图片的问题是咋回事啊，记得这个库我半年前用的时候是好好的。
怎么现在越来越多的bug了，作者是换人了吗？

**Comment by WilliamLin1990** [comment]
@zgj233 前几天在微信上问了作者，但是后来也没回复了，可能作者太忙了吧，我现在使用vue-croppa先顶着用了。

**Comment by JackPu** [comment]
@zgj233 @WilliamLin1990 黑屏问题修复了，是之前引用库的问题导致，还有就是和你们需求理解的有些出入引起的。 `2.4.10` 版本

**Comment by JackPu** [comment]
@565784135  `credentials ` 这个众口难调，最起初的版本是不设置这个值的，但是后期有些用户需要，所以这个只能我在文档备注下咯。
