### ISSUE TITLE
建议：裁剪图片可以在本地裁剪吗？

### ISSUE THREAD

**Issue by Sapphire2k** [Vanthink-UED/vue-core-image-upload#20]
就是在选择了照片之后直接对图片进行裁剪，
样式可以考虑一下这个
[vue-crop](http://pespantelis.github.io/vue-crop/)
体验会好很多～ 
嘿嘿

**Comment by JackPu** [comment]
@Sapphire2k 支持的，有crop属性来确定是否裁剪，demo最下面那个是裁剪的演示哦，
![image](https://cloud.githubusercontent.com/assets/4744967/23291444/95164a48-fa93-11e6-9be4-fdc14904caaf.png)

我们后面会改成这种形式的样式，😁💐。

**Comment by Sapphire2k** [comment]
嘿嘿 我看到这个啦～不是很友好 不过 够用了嘿嘿
