### ISSUE TITLE
在 Bootstrap modal dialog 上弹出剪裁窗口图片错位

### ISSUE THREAD

**Issue by jhzzzz** [Vanthink-UED/vue-core-image-upload#21]
在bootstrap 弹窗窗口上嵌入 vue-core-image-upload，并设置crop=true，结果文件上传后，弹出调整窗口上图片错位了，无法正常显示。

**Comment by JackPu** [comment]
您能给我看一下截图什么的，方便排查？

**Comment by jhzzzz** [comment]
![error](https://cloud.githubusercontent.com/assets/6584445/23488882/4acec082-ff2a-11e6-89bd-cc3b6725c8f4.PNG)

你好，如图，在有modal dialog情况下，弹出层不能撑满屏幕，我看了下代码，貌似是长宽计算的时候出了问题。

**Comment by JackPu** [comment]
我知道了什么情况了我尽快fix这个问题吧后面你更新下就好了。

**Comment by YukiYuko** [comment]
请问一下 这个问题解决了吗
