### ISSUE TITLE
建议：能否增加上传图片前先压缩图片

### ISSUE THREAD

**Issue by Sapphire2k** [Vanthink-UED/vue-core-image-upload#22]
找了一下，发现这个插件还挺不错的 https://github.com/think2011/localResizeIMG

**Comment by JackPu** [comment]
这个应该不会支持，这个需求可能不是特别多，我会想办法暴露接口让你使用压缩这个插件

**Comment by AdoneZ** [comment]
感觉这个功能还挺有用的。。。现在木有只有自己写Canvas了

**Comment by Sapphire2k** [comment]
还挺刚需的，毕竟移动端一张图片 就好几m了～

**Comment by AdoneZ** [comment]
对呀，这个剪裁好像也不能直接用么，需要获取到参数然后自己发送给服务器么，我在本地剪裁的话，需要自己剪裁了然后压缩了再上传0.0

**Comment by JackPu** [comment]
@Sapphire2k 嗯，对移动端确实这个需求很大。
@AdoneZ 目前是裁剪只通过服务端获取参数进行处理。

**Comment by AdoneZ** [comment]
@JackPu 剪裁的参数怎么获取呢，就是文档里面写的toCropImg这些

**Comment by JackPu** [comment]
你在服务端 node 或者 php  post的查询参数就有

**Comment by AdoneZ** [comment]
好吧，谢谢

**Comment by JackPu** [comment]
新版本支持了本地裁剪和压缩: http://vanthink-ued.github.io/vue-core-image-upload/index.html#/en/compress-image
