### ISSUE TITLE
引入之后一直说无法找到

### ISSUE THREAD

**Issue by AdoneZ** [Vanthink-UED/vue-core-image-upload#23]
This dependency was not found in node_modules:

* ./vue.core.image.upload

**Comment by AdoneZ** [comment]
找到原因了，原来是模块化安装的直接引用文件夹名称就行了

**Comment by AdoneZ** [comment]
对了，我在.vue文件里面发现了一个CSS报错0.0，多了一个逗号.g-core-image-corp-container .btn:active,{

**Comment by JackPu** [comment]
I am so sorry about demo code.  I'll fixed it soon.😢

**Comment by JackPu** [comment]
You could update the npm package to 2.0.6 ! I have fixed the stupid error.

**Comment by AdoneZ** [comment]
OK!  THANKS.
