### ISSUE TITLE
改变不了大小了，需要设置什么参数么

### ISSUE THREAD

**Issue by AdoneZ** [Vanthink-UED/vue-core-image-upload#24]
`<vue-core-image-upload
          :class="['pure-button','pure-button-primary','js-btn-crop']"
          v-bind:crop="true"
          :cropBtn="{ok:'保存',cancel:'取消'}"
          crop-ratio="1:1"
          v-on:imageuploaded="imageuploaded"
          text="选择头像"
          extensions="png,jpeg,jpg"
          input-accept="image/*">
        </vue-core-image-upload>`
我看了一下，我自己的拖动的DIV上和例子里面差了一个LOAD事件

**Comment by JackPu** [comment]
不需要啊，你那边的版本是多少？

**Comment by AdoneZ** [comment]
2.0.6 我正在把VUE拉出来单独测。。。

**Comment by JackPu** [comment]
@AdoneZ  你重新安装下最新的版本2.0.7，应该是小版本文件的问题.

**Comment by AdoneZ** [comment]
现在可以动了，但是会主动的POST，但是我没有写URL，我也不想要他上传呀0.0

**Comment by JackPu** [comment]
@AdoneZ  如果你不想上传的话有个isXhr 的选项你设置为false就会把图片处理交给你自己定义了

**Comment by AdoneZ** [comment]
好了，谢谢啊
