### ISSUE TITLE
手机上传的图片，纵向图片会变成横向

### ISSUE THREAD

**Issue by AdoneZ** [Vanthink-UED/vue-core-image-upload#26]
安卓上会剪裁一部分图片，IOS上会将原图拉伸，这个仿佛要修改图片的EXIF

**Comment by JackPu** [comment]
@AdoneZ  你能传一张截图么？我这边测试没有遇见这种情况。

**Comment by AdoneZ** [comment]
![screenshot_20170318-163354](https://cloud.githubusercontent.com/assets/9249643/24070455/f4cd023a-0bf8-11e7-86db-89a026ab472e.png)

**Comment by JackPu** [comment]
这个是照片的问题吧。

**Comment by AdoneZ** [comment]
不是啊，安卓直接传进来就是横着的。。。苹果是竖着的。。。

**Comment by JackPu** [comment]
@AdoneZ  麻烦你罚下图片给我，我用自己手机测试下？

**Comment by AdoneZ** [comment]
我不晓得图片发过来会不会被修改啊。。。还是从邮件发过去比较靠谱

**Comment by JackPu** [comment]
嗯，你发我gmail吧，github有联系方式。

**Comment by vFire** [comment]
这个问题貌似五花八门，建议留旋转按钮给resize界面，让用户自行调整。

**Comment by xuzicn** [comment]
这重情况是因为iOS手机拍摄的图片的EXIF内是带有方向信息的，参看这个库
https://github.com/exif-js/exif-js

**Comment by davy-gan** [comment]
希望作者能将这个旋转的问题加入新版本中，目前ios手机拍出来的照片都会旋转的

**Comment by JackPu** [comment]
新版本发布了旋转的按钮~ version : 2.3.x

**Comment by zhangyuanze** [comment]
求指教，文档中没看到可以让图片旋转的操作啊
