### ISSUE TITLE
这个不能在本地裁剪吗？

### ISSUE THREAD

**Issue by ghost** [Vanthink-UED/vue-core-image-upload#27]
图片裁剪必须在服务器上进行？

**Comment by JackPu** [comment]
@shoyuf  目前是不支持的，但是这个已经放到需求排期了，更新会艾特你的。

**Comment by JackPu** [comment]
已经支持： 详见 http://vanthink-ued.github.io/vue-core-image-upload/index.html#/en/crop-image
