### ISSUE TITLE
一次上传多张图片怎么上传

### ISSUE THREAD

**Issue by zhouyu1993** [Vanthink-UED/vue-core-image-upload#28]
一次上传多张图片怎么上传

**Comment by JackPu** [comment]
@zhouyu1993  目前不支持多张图片上传，因为之前有裁剪的支持，所以目前这个需求是在队列中的，后期会实现。

**Comment by JackPu** [comment]
支持多文件上传，文档详见这里http://vanthink-ued.github.io/vue-core-image-upload/index.html#/cn/multiple-file

**Comment by zhouyu1993** [comment]
好的，观摩一下！😊
