### ISSUE TITLE
如何携带额外参数？

### ISSUE THREAD

**Issue by mn8821236** [Vanthink-UED/vue-core-image-upload#29]
需要通过这个上传用户头像，但是需要携带uid，不知道怎么处理。通过文档给的header添加参数，报错Request header field auth is not allowed by Access-Control-Allow-Headers in preflight response

**Comment by mn8821236** [comment]
通过直接修改源码，自行添加了个prop参数

**Comment by JackPu** [comment]
您好，这个应该是支持过得，你可以修改源码然后提个PR给我。data Prop.

**Comment by Frisco22** [comment]
我也遇到了同样的问题，请问怎么处理，越详细越好。如果修改源码改怎么修改

**Comment by JackPu** [comment]
@Frisco22   @mn8821236  最新版本已经支持了这个需求，你们可以更新这个包就行了。文档已经更新了。`<vue-core-image-upload :data="someData" ...`

**Comment by mn8821236** [comment]
好谢谢
