### ISSUE TITLE
是否有支持vue 2.0的计划？

### ISSUE THREAD

**Issue by BruinY** [Vanthink-UED/vue-core-image-upload#3]
是否有支持vue 2.0的计划？

**Comment by JackPu** [comment]
@BruinY 开发中 😁 完成后艾特你吧，

**Comment by xukaifu** [comment]
你好， 支持vue2.0了吗

**Comment by BruinY** [comment]
@xukaifu 估计还没有吧，这个开发团队好像挺忙的

**Comment by JackPu** [comment]
@BruinY @xukaifu  2.0在计划中，几天后就可以弄完，

**Comment by JackPu** [comment]
Vue.js(>=2.0) support project  https://github.com/JackPu/vue2.x-core-image-upload ,We will merge it in the future😊.
