### ISSUE TITLE
无法触发父组件更新src的值？

### ISSUE THREAD

**Issue by doforgrace** [Vanthink-UED/vue-core-image-upload#33]
`<script>
    import VueCoreImageUpload from "vue-core-image-upload"
    export default{
        data(){
            return{
                src: 'http://img1.vued.vanthink.cn/vued0a233185b6027244f9d43e653227439a.png'
            }
        },
        components:{
            'vue-core-image-upload': VueCoreImageUpload
        },
        methods: {
            imageUploaded(res) {
                console.log("111")
                if(res.errcode==0){
                    this.src="http://img1.vued.vanthink.cn/vued751d13a9cb5376b89cb6719e86f591f3.png"
                }
            },
            errorhandle(err) {
                  console.error(err);
            }
        }
    }

</script>
`

**Comment by doforgrace** [comment]
DEMO中描述有错误，调用组件中没有 v-on:imageuploaded="imageUploaded"

**Comment by JackPu** [comment]
@doforgrace 收到～ Thanks a lot 💐
