### ISSUE TITLE
bower 更新 2.0 提示版本错误

### ISSUE THREAD

**Issue by BruinY** [Vanthink-UED/vue-core-image-upload#34]
bower vue-core-image-upload#v2.0           cached https://github.com/Vanthink-UED/vue-core-image-upload.git#v2.0
bower vue-core-image-upload#v2.0         validate v2.0 against https://github.com/Vanthink-UED/vue-core-image-upload.git#v2.0
bower vue#^1.0.26                          cached https://github.com/vuejs/vue.git#1.0.28
bower vue#^1.0.26                        validate 1.0.28 against https://github.com/vuejs/vue.git#^1.0.26
Please note that,
    vue-core-image-upload#v2.0 depends on vue#^1.0.26 which resolved to vue#1.0.28
    asp.net depends on vue#v2.2.6 which resolved to vue#2.2.6
Resort to using vue#v2.2.6 which resolved to vue#2.2.6
Code incompatibilities may occur.
bower vue-core-image-upload      extra-resolution Unnecessary resolution: vue-core-image-upload#1.0.0

**Comment by JackPu** [comment]
@BruinY  应该是没传，我传下就好，

**Comment by BruinY** [comment]
希望能尽快更新好，谢谢

**Comment by JackPu** [comment]
@BruinY  已经更新，但是官网建议不再使用 bower , 建议你使用 yarn 或者 npm 

![image](https://cloud.githubusercontent.com/assets/4744967/24825557/3a175146-1c53-11e7-8813-8d0edbd49710.png)
