### ISSUE TITLE
能否实现客户端裁剪？

### ISSUE THREAD

**Issue by BruinY** [Vanthink-UED/vue-core-image-upload#36]
建议使用客户端裁剪图片，然后直接提交base64数据到服务器端，而不是现在原图上传，并提交裁剪位置。使用客户端裁剪，base64数据提交，更有利于节约网络流量提高速度。

**Comment by JackPu** [comment]
关于裁剪，最新版本已经发布了。http://vanthink-ued.github.io/vue-core-image-upload/index.html#/cn/crop-image
