### ISSUE TITLE
老板，能不能把组件同步发布到 Bower

### ISSUE THREAD

**Issue by BruinY** [Vanthink-UED/vue-core-image-upload#4]
NPM有的时候会很卡。访问失败。能不能同步发布到 Bower

**Comment by JackPu** [comment]
@BruinY  OK 😄，

**Comment by BruinY** [comment]
另外最好是输出单js文件引用来使用。考虑一下一些新手。只有降低门槛和易用，组件才会被宣传开来。大量的普通程序员，实际上并不会用那些打包工具以及ES6

**Comment by JackPu** [comment]
👌，好的建议，我们会尽快加入计划。

**Comment by BruinY** [comment]
@JackPu 什么时候输出单js文件，和发布到bower?

**Comment by JackPu** [comment]
@BruinY  已经发布了你可以试下
`bower install vue-core-image-upload`

**Comment by BruinY** [comment]
@JackPu 能够正常获取到。
单js文件，这个计划搞吗？计划搞就等你们弄好。不然只能自己打包一下了。

**Comment by JackPu** [comment]
嗯，我们会在今明两天弄完，

**Comment by JackPu** [comment]
@BruinY  文档更新了 单文件的使用

**Comment by BruinY** [comment]
@JackPu 给你们点赞。。

**Comment by BruinY** [comment]
@JackPu 给你们点赞。。

**Comment by JackPu** [comment]
@BruinY  谢谢支持 💐😊
