### ISSUE TITLE
请问我选择传入服务器的时候文件为空，不知道为什么，能帮助我吗？

### ISSUE THREAD

**Issue by pzuopin** [Vanthink-UED/vue-core-image-upload#41]
这是我的配置：

       :url="uploadUrl"
        :text="'Upload Image'"
        :crop="false"
        :inputOfFile="'file'"
        input-accept="image/*"
        :maxFileSize="5242880"
        @imageuploaded="imageuploaded"
        @errorhandle="errorhandle"
        extensions="png,gif,jpeg,jpg"

  在vue里组件引用

传入服务器的时候判别  表示文件为空，能帮忙吗？谢谢

**Comment by pzuopin** [comment]
我发现  inputOfFile 默认的好像是 files  不是file    所以服务器端接收失败  现在正常了， 谢谢你们的代码， 希望越来越多的人受益！！！

**Comment by pzuopin** [comment]
发现一个新的问题  安卓微信部分图片选择有问题 显示Type ERR  而这个图片是png格式 在允许范围内的

**Comment by JackPu** [comment]
@pzuopin  你的意思是说修改了 `inpoutOfFile` 无效是吧？
