### ISSUE TITLE
你确定支持ie9？formdata在ie9不生效的

### ISSUE THREAD

**Issue by vcxiaohan** [Vanthink-UED/vue-core-image-upload#42]

**Comment by JackPu** [comment]
formData 在IE上不支持，支持到IE11 和 Edge

**Comment by vcxiaohan** [comment]
> a vue plugin for image upload and crop ( Support :iphone: IE9+)

README里面写的支持ie9+，ie9不支持，ie10应该是可以的，麻烦测试一下呢

**Comment by JackPu** [comment]
已经更新了文档，谢谢指出错误 💐

**Comment by WildDylan** [comment]
可否支持IE9
