### ISSUE TITLE
根本用不了啊哥

### ISSUE THREAD

**Issue by ijry** [Vanthink-UED/vue-core-image-upload#45]
直接报错什么json错

**Comment by JackPu** [comment]
@ijry  什么问题？如果方便的话可以加下我 760341479都微信QQ都可以可以，

**Comment by ijry** [comment]
我是这样才才使用成功
import VueCoreImageUpload from '../../../../../../node_modules/vue-core-image-upload/src/vue.core.image.upload.vue';

例子里的下面这句用了不行
import VueCoreImageUpload from 'vue-core-image-upload'

**Comment by JackPu** [comment]
？？??  你的结构目录是怎样的？

**Comment by ijry** [comment]
![default](https://cloud.githubusercontent.com/assets/3102798/25801343/b44ebe02-341f-11e7-9ca4-2fa7b256f2b5.PNG)

这样的

**Comment by ijry** [comment]
一用import VueCoreImageUpload from 'vue-core-image-upload'就出现下图的错误
![1](https://cloud.githubusercontent.com/assets/3102798/25801359/d76b1f8e-341f-11e7-9ad6-715100ffa743.PNG)

**Comment by JackPu** [comment]
你更新下，应该文件已经改变了，
