### ISSUE TITLE
裁剪拖拽有问题

### ISSUE THREAD

**Issue by BruinY** [Vanthink-UED/vue-core-image-upload#5]
裁剪图片拖拽裁剪区域的时候存在比较严重的bug，老自动到最右，无法正常进行拖拽

**Comment by JackPu** [comment]
@BruinY  我看下，应该是版本问题，之前没有出现过这样的问题，

**Comment by BruinY** [comment]
现在所有的浏览器都是这样的情况

**Comment by didida** [comment]
同遇到这个问题

**Comment by BruinY** [comment]
我建议取消这种拖拽设计。转而使用固定区域。然后另外去控制图片放大缩小和图片移动。实际上的引用场景，都会固定裁剪大小。这样做，还有利于兼容移动端。

**Comment by BruinY** [comment]
目前获取到的新版依旧存在这个问题。包括demo地址的上传裁剪，也是一样的。

**Comment by BruinY** [comment]
莫非现在在开发2.0，没有时间来修复这个bug?

**Comment by angusjiang** [comment]
@BruinY 原本只是在移动端开发所以没有pc注意浏览器的兼容性，目前已经修复， 等待上穿中，目前只支持主流浏览器，没有兼容IE。

**Comment by BruinY** [comment]
demo 已经看到更新了。赞
