### ISSUE TITLE
text属性可以修改为Slot么

### ISSUE THREAD

**Issue by lesonli** [Vanthink-UED/vue-core-image-upload#52]
因为上传按钮有可能是个图标或者图片，text只能设置纯文本，slot就可以随便放内容进去了。

**Comment by lesonli** [comment]
<div class="g-core-image-upload-btn">
    {{text}}
修改为：
    <div class="g-core-image-upload-btn">
    <slot></slot>

**Comment by JackPu** [comment]
这个已经在做了哈，

**Comment by JackPu** [comment]
@lesonli  已经支持了 http://vanthink-ued.github.io/vue-core-image-upload/index.html#/en/custom-component
