### ISSUE TITLE
js 里用es6的写法在build的时候压缩失败

### ISSUE THREAD

**Issue by lin-xin** [Vanthink-UED/vue-core-image-upload#56]
src/lib/helper.js 里用 es6 的写法，当我执行 run npm build 的时候会报错，

ERROR in static/js/1.9b54ed3abbb94278af64.js from UglifyJs
Unexpected character '`' [./~/vue-core-image-upload/src/lib/helper.js:11,0][static/js/1.9b54ed3abbb94278af64.js:39,18]

**Comment by JackPu** [comment]
@这个你配置下babel吧。

**Comment by lin-xin** [comment]
我自己.vue里面的就可以啊，但是node_modules里的就不行

**Comment by JackPu** [comment]
你用的wevpack2?

**Comment by lin-xin** [comment]
是啊

**Comment by guadan2001** [comment]
因为UglifyJs不支持es2015，所以自己把那几个js全改了，把let改成var，还有几个函数的声明，还有一个return {left, top}改成return {left: left, top: top}

**Comment by JackPu** [comment]
😂 你更新就好，我已经全部转了。

**Comment by lin-xin** [comment]
@JackPu 谢谢
