### ISSUE TITLE
XMLHttpRequest cannot load http://172.168.66.110:20803/borrower/upload. 

### ISSUE THREAD

**Issue by yksmile007** [Vanthink-UED/vue-core-image-upload#59]
XMLHttpRequest cannot load http://172.168.66.110:20803/borrower/upload. The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'http://localhost:8081' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.
xhr.js?b8c9:1 SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.p.onerror (eval at <anonymous> (app.js:2508), <anonymous>:52:22)
一直报这个错误

**Comment by JackPu** [comment]
关于跨域上传的问题可以参考这里  http://www.cnblogs.com/Darren_code/p/cors.html

**Comment by yksmile007** [comment]
:headers="{'Access-Control-Allow-Origin':'*'}"
加了这个属性之后，还是报同样的错误

**Comment by JackPu** [comment]
跨域需要服务端支持的，你可以看我的demo里面服务端返回的 header里面的设计，我那个是用php写的。

**Comment by yksmile007** [comment]
XMLHttpRequest cannot load http://172.168.66.110:20803/borrower/upload. The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'http://localhost:8081' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.p.onerror (eval at <anonymous> (app.js:2526), <anonymous>:52:22)
一直报这个错误，怎么回事？

**Comment by JackPu** [comment]
你截个你返回的http响应的截图？

**Comment by JackPu** [comment]
关于关于的问题，可以参考php的实现 [Code](https://github.com/Vanthink-UED/vue-core-image-upload/blob/master/site/server/upload.php)，重点是控制header头的返回。

**Comment by 531431988** [comment]
![qq 20170524174032](https://cloud.githubusercontent.com/assets/8703951/26397309/7921ecf6-40a8-11e7-8109-b19920c0bfd0.png)

我也遇到这个问题，求指点，后台人员说不是跨域

**Comment by JackPu** [comment]
关于 boundary 这个问题已经修复了
