### ISSUE TITLE
建议把裁剪页面的按钮改为自定义

### ISSUE THREAD

**Issue by BruinY** [Vanthink-UED/vue-core-image-upload#6]
建议把裁剪页面的按钮改为自定义，以满足不同语言的需求。另外目前ES5单文件，只有CDN，通过bowser获取到的源码中并不包含。

**Comment by JackPu** [comment]
但文件就在项目index.js ，你可以自行处理它，然后已经支持自定义按钮含义了，可以见readme.md

**Comment by BruinY** [comment]
相应还挺快。给你们点赞
