### ISSUE TITLE
[Vue warn]: "class" is a reserved attribute and cannot be used as component prop.

### ISSUE THREAD

**Issue by chhfhjv** [Vanthink-UED/vue-core-image-upload#62]
[Vue warn]: "class" is a reserved attribute and cannot be used as component prop.

**Comment by chhfhjv** [comment]
<vue-core-image-upload :class="['pure-button','pure-button-primary','js-btn-crop']"
                               :crop="true"
                               :data="data"
                               text="上传图片"
                               url="/api/posts/"
                               extensions="png,gif,jpeg,jpg"
                               @imageuploaded="imageuploaded"
                               @errorhandle="handleError"></vue-core-image-upload>

**Comment by JackPu** [comment]
最细版本已经修复了 `class="pure-button pire-button-primary js-btn-crop"` 这样写吧

**Comment by vFire** [comment]
Great! 刚发现这个问题就解决了~

**Comment by chhfhjv** [comment]
谢谢，知道了
