### ISSUE TITLE
裁剪区域能设置固定大小吗？

### ISSUE THREAD

**Issue by BruinY** [Vanthink-UED/vue-core-image-upload#7]
裁剪区域能设置固定大小吗？就是根据配置设定固定大小，不允许调整裁剪框的大小。现在的配置参数里面只有最大裁剪尺寸

**Comment by BruinY** [comment]
想了想，好像这必要也不是特别大，关闭这个工单了

**Comment by JackPu** [comment]
@BruinY  需求方面这个会在需求列表里，但是优先级不一样，不一定会非常快速的上新的需求功能，希望理解，
