### ISSUE TITLE
vue-cli 2.0 

### ISSUE THREAD

**Issue by wangxiahui007** [Vanthink-UED/vue-core-image-upload#71]
Module parse failed: G:\project\huaxing\ice-sports\ice-sports\node_modules\._vue-core-image-upload@2.2.2@vue-core-image-upload\dist\vue-core-image-upload.vue Unexpected token (1:0)
You may need an appropriate loader to handle this file type.

**Comment by JackPu** [comment]
这个问题已经 fixed ~
