### ISSUE TITLE
配置参数不起作用

### ISSUE THREAD

**Issue by BruinY** [Vanthink-UED/vue-core-image-upload#8]
不知道是不是哪里用错了。配置参数不起作用。。。除了几个参数，完全按照说明来的
inputOfFile，cropBtn，inputAccept 这几个参数完全无效
`<vue-core-image-upload crop-ratio="1.505:1"
                                       v-bind:class="['pure-button','pure-button-primary','js-btn-crop']"
                                       v-bind:crop="true"
                                       inputOfFile="file"
                                       url="/upload"
                                       text="点击上传封面图片"
                                       cropBtn="{ok:'Save','cancel':'Give Up'}"
                                       inputAccept="image/gif,image/jpg,image/jpeg,image/png"
                                       extensions="png,gif,jpeg,jpg">
                </vue-core-image-upload>`

**Comment by BruinY** [comment]
为什么文档是说的 inputAccept 不生效，而demo上却是input-accept，换上这个之后，生效了。

inputOfFile 依旧不行。cropBtn 也依旧不行

**Comment by JackPu** [comment]
应该行的哦，你看下是不是文件太老了。
