### ISSUE TITLE
组件应该提供 input file的 change事件回调接口

### ISSUE THREAD

**Issue by luxueyan** [Vanthink-UED/vue-core-image-upload#9]
我觉得直接配置上传的url写的太死，无法满足我自己处理图片的需求，希望多提供的事件回调接口

**Comment by JackPu** [comment]
嗯，谢谢支持，我们会尽快设计的。@luxueyan

**Comment by JackPu** [comment]
@luxueyan 最新版本 增加了对imagechanged 的事件响应。
