### ISSUE TITLE
Sending the uploaded image and text via a button instead?

### ISSUE THREAD

**Issue by maryheng** [Vanthink-UED/vue-core-image-upload#94]
Hi all,

Is there a way for me to send the image and the data (inputs from input fields) via a Submit button which will then POST to the server? Instead of after uploading an image, it immediately POST the data to the server?

Any sample codes?

Appreciate the help! Thanks!

**Comment by maryheng** [comment]
大家好，

有没有办法通过提交按钮发送图像和数据（输入字段的输入），然后POST到服务器？上传图像后，它立即将数据POST到服务器？

任何示例代码？

欣赏帮助！谢谢！

**Comment by JackPu** [comment]
You can view document and code [here](http://vanthink-ued.github.io/vue-core-image-upload/index.html#/en/post-data)
